# Generated by Django 2.1.4 on 2018-12-08 08:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('date', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('movie', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
