# Generated by Django 2.1.4 on 2018-12-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
